project_id = "tyjyvwvfmscehejdyiis"

[functions.scrape-caixa]
verify_jwt = false

[functions.manage-staging]
verify_jwt = false

[functions.import-property]
verify_jwt = false

[functions.import-property-screenshot]
verify_jwt = false
